Multi Region AvailabilityZone selection of mac instances
runfinch/infrastructure pull request #182
Opened 2023-03-10 22:02 UTC by monirul

*Issue #, if available:*

*Description of changes:*
Previously, the default value of availability zone was hardcoded to `west-us2`. This was preventing us to deploy mac instances for other regions such as `east-us2` for release infra. To support multi region, this PR made two changes:
1. Instead of hardcoding the default availability zone to `west-us2`, now we can pass it as part of mac config parameter for each instance.
2. To select the availability zone from the cdk context, previously it used to select the 4th elements from the availabilityzone list. But not all region has 4 or more availability zone. To fix this this PR selects the last availability zone from the list instead.

*Testing done:*
I have tested this code by running `cdk synth` in local computer.

- [x] I've reviewed the guidance in CONTRIBUTING.md

#### License Acceptance

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-03-10 22:26 UTC, pendo324 requested changes
Left some notes and a nit to clean up the formatting

2023-03-10 22:26 UTC, pendo324 commented on lib/finch-pipeline-app-stage.ts
> +    }
nit: formatting
```suggestion
    // set the availability zone.
    const availabilityZones = this.node.tryGetContext('availabilityZones');
    const selectedAvailabilityZone = availabilityZones?.[availabilityZones?.length - 1] ?? config.defaultAvailabilityZone;
```

2023-03-10 22:26 UTC, pendo324 commented on lib/finch-pipeline-app-stage.ts
> +    }
This also means that the sequentially last availability zone will be used in preference to the `defaultAvailabilityZone`. That makes it easier to deploy to other regions, because you don't have to provide a static availability zone, but it also means its less "deterministic". Also, the availability zone is not tied to the region with this code, which I guess is fine because that's probably difficult to achieve. This means that if the list of availabilityZones from the context is empty, it could try to provision a macOS host in us-east-1, but with the `defaultAvailabilityZone` of e.g. `us-west-2d`. Seems fine to me, since the previous experience when trying to deploy to a different region was even worse, but it would be nice if there was a better way to do this (maybe just remove the default and throw an error if the context doesn't have `availabilityZones`? Not sure, don't have to fix it now, just wanted to call it out.

2023-03-11 00:05 UTC, monirul commented on lib/finch-pipeline-app-stage.ts
> +    }
Good point. For now, I added an TODO for future.

2023-03-11 00:43 UTC, pendo324 commented on lib/finch-pipeline-app-stage.ts
> +    var selectedAvailabilityZone = availabilityZones?.at(-1) ?? config.defaultAvailabilityZone;
This is definitely better than what I posted, I forgot this feature was added to JS, nice.

nit: can you use `const` here instead of `var` to keep the code consistent? In modern JS `var` is typically avoided due to scoping/hoisting issues ([more info](https://medium.com/@codingsam/awesome-javascript-no-more-var-working-title-999428999994)).

2023-03-11 00:43 UTC, pendo324 commented on lib/finch-pipeline-app-stage.ts
> +    //TODO: Improve the availability zone selection logic. Instead of assigning default availability zone, we can throw exception
nit: can you add a space to the comment? `// TODO` instead of `//TODO`? Just to keep it more consistent with other files/comments

2023-03-11 00:59 UTC, pendo324 approved these changes
Feel free to merge (preferably with my nits addressed 😄), but don't feel like you need another review from me to merge

2023-03-13 18:12 UTC, monirul commented on lib/finch-pipeline-app-stage.ts
> +    var selectedAvailabilityZone = availabilityZones?.at(-1) ?? config.defaultAvailabilityZone;
Good point. Changed.

2023-03-13 18:12 UTC, monirul commented on lib/finch-pipeline-app-stage.ts
> +    //TODO: Improve the availability zone selection logic. Instead of assigning default availability zone, we can throw exception
Done.

2023-03-13 18:14 UTC, weikequ approved these changes

2023-03-13 18:21 UTC, azhouwd approved these changes

2023-03-13 19:10 UTC, merged